### ISSUE TITLE
Failing to compile with default

### ISSUE THREAD

**Issue by gman77** [SAP-samples/ui5-webcomponents-sample-angular#33]
Following the instructions, however when building using npm start

ERROR in ./src/app/app.module.ts
Module not found: Error: Can't resolve '@ui5/webcomponents-base/dist/features/browsersupport/Edge' in '/Users/Documents/sap/upscale/ui5-webcomponents-sample-angular/src/app'
ℹ ｢wdm｣: Failed to compile.

Remarking out the following line in app.module.ts, allows compile:
// import "@ui5/webcomponents-base/dist/features/browsersupport/Edge";

Maybe just update the documentation or have it commented out by default and those that use Microsoft Browsers can enable.

**Comment by ilhan007** [comment]
Hello @gman77 the 'import "@ui5/webcomponents-base/dist/features/browsersupport/Edge";' is now removed the docs are updated
